parameters:
#    catalyst_log.example.class: Catalyst\LogBundle\Example

services:
    catalyst_log:
        class: Catalyst\LogBundle\Model\LogManager
        arguments: ["@service_container"]
#    catalyst_log.example:
#        class: %catalyst_log.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
