acl:
    - category: Online Forms
      entries:
        - id: ser_forms.menu
          label: "Menu"
    - category: Pull Out Forms
      entries:
        - id: ser_pullout.menu
          label: "Menu"
        - id: ser_pullout.view
          label: "View"
        - id: ser_pullout.add
          label: "Add"
        - id: ser_pullout.edit
          label: "Edit"
        - id: ser_pullout.delete
          label: "Delete"
    - category: Job Order Forms
      entries:
        - id: ser_repair.menu
          label: "Menu"
        - id: ser_repair.view
          label: "View"
        - id: ser_repair.add
          label: "Add"
        - id: ser_repair.edit
          label: "Edit"
        - id: ser_repair.approve
          label: "Approve"
        - id: ser_repair.send
          label: "Send"
        - id: ser_repair.fulfill
          label: "Fulfill"
        - id: ser_repair.cancel
          label: "Cancel"