menu_items:
    - id: menu_forms
      acl: ser_forms.menu
      label: Online Forms
      icon: fa-file
    - id: ser_pullout_index
      acl: ser_pullout.menu
      label: Pull Out Forms
      parent: menu_forms
    - id: ser_repair_index
      acl: ser_repair.menu
      label: Job Order Forms
      parent: menu_forms
