services:
    catalyst_media:
        class: Catalyst\MediaBundle\Model\UploadManager
        arguments: ['%catalyst_media.storage_config%', '@security.token_storage', '@doctrine.orm.entity_manager']

#    catalyst_media.example:
#        class: Catalyst\MediaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
