ser_inv_wh_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:index }

ser_inv_wh_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:addForm }

ser_inv_wh_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:addSubmit }

ser_inv_wh_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:editForm }

ser_inv_wh_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:editSubmit }

ser_inv_wh_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:delete }

ser_inv_wh_stock_grid:
    pattern: /grid/{id}/stock
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:stockGrid }

ser_inv_wh_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:ajaxGet }

ser_inv_wh_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaAdminBundle:Warehouse:grid }
