parameters:
#    catalyst_dashboard.example.class: Catalyst\DashboardBundle\Example

services:
#    catalyst_dashboard.example:
#        class: %catalyst_dashboard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
