cat_pur_po_index:
    path:    /pos
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:index }

cat_pur_po_add_form:
    path:    /po
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:addForm }

cat_pur_po_add_submit:
    pattern: /po
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:addSubmit }

cat_pur_po_edit_form:
    pattern: /po/{id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:editForm }

cat_pur_po_edit_submit:
    pattern: /po/{id}
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:editSubmit }

cat_pur_po_delete:
    pattern: /po/{id}/delete
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:delete }

cat_pur_po_grid:
    pattern: /pos/grid
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:grid }

cat_pur_po_get_purchase_request:
    pattern: /po/purchase_request/{id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseOrder:getPurchaseRequest, id: null }


cat_pur_pr_index:
    pattern: /prs
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:index }

cat_pur_pr_add_form:
    pattern: /pr
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:addForm }

cat_pur_pr_add_submit:
    pattern: /pr
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:addSubmit }

cat_pur_pr_add_entry:
    pattern: /pr/add/{entry_id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:addEntry }

cat_pur_pr_add_entry_submit:
    pattern: /pr/add/{entry_id}
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:addEntrySubmit }

cat_pur_pr_edit_form:
    pattern: /pr/{id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:editForm }

cat_pur_pr_edit_submit:
    pattern: /pr/{id}
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:editSubmit }

cat_pur_pr_delete:
    pattern: /pr/{id}/delete
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:delete }

cat_pur_pr_grid:
    pattern: /prs/grid
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:grid }

cat_pur_pr_ajax_get:
    pattern: /ajax/pr/{id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:ajaxGet }

cat_pur_pr_status_approve:
    pattern: /pr/{id}/status/approve
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:statusApprove }

cat_pur_pr_status_cancel:
    pattern: /pr/{id}/status/cancel
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:statusCancel }

cat_pur_pr_type:
    pattern: /pr/type/{type_id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:getType }

cat_pur_pr_product:
    pattern: /pr/product/{prod_id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:PurchaseRequest:getProduct }


