feac_pur_po:
    path:    /pos
    defaults: { _controller: FareastPurchasingBundle:Purchase:index }

feac_pur_po_add_form:
    path:    /po
    defaults: { _controller: FareastPurchasingBundle:Purchase:addForm }

feac_pur_po_add_submit:
    pattern: /po
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:Purchase:addSubmit }

feac_pur_po_edit_form:
    pattern: /po/{id}
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:Purchase:editForm }

feac_pur_po_edit_submit:
    pattern: /po/{id}
    methods: [POST]
    defaults: { _controller: FareastPurchasingBundle:Purchase:editSubmit }

feac_pur_po_delete:
    pattern: /po/{id}/delete
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:Purchase:delete }

feac_pur_po_grid:
    pattern: /pos/grid
    methods: [GET]
    defaults: { _controller: FareastPurchasingBundle:Purchase:grid }



feac_pur_req:
    path:     /requisition
    defaults: { _controller: FareastPurchasingBundle:Requisition:index }

feac_pur_req_add:
    path:     /requisition/add
    defaults: { _controller: FareastPurchasingBundle:Requisition:add }