config:
    - category: "Inventory"
      entries:
        - id: catalyst_supplier_warehouse_default
          label: "Default Supplier Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
