menu_items:
    - id: ser_order
      acl: ser_order.menu
      label: Requisitions
      icon: fa-truck
    - id: ser_pur_pr_index
      acl: ser_pur_pr.menu
      label: Requested Items
      parent: ser_order
    - id: ser_receive_index
      acl: ser_receive.menu
      label: Incomplete Deliveries
      parent: ser_order
    - id: ser_complete_index
      acl: ser_complete.menu
      label: Completed Deliveries
      parent: ser_order
    - id: ser_rlist_index
      acl: ser_rlist.menu
      label: Requested Items List
      parent: ser_order
    - id: ser_dlist_index
      acl: ser_dlist.menu
      label: Deliveries List
      parent: ser_order
