ser_pur_pr_index:
    pattern: /prs
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:index }

ser_pur_pr_add_form:
    pattern: /pr
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:addForm }

ser_pur_pr_add_submit:
    pattern: /pr
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:addSubmit }

ser_pur_pr_add_entry:
    pattern: /pr/add/{entry_id}
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:addEntry }

ser_pur_pr_add_entry_submit:
    pattern: /pr/add/{entry_id}
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:addEntrySubmit }

ser_pur_pr_edit_form:
    pattern: /pr/{id}
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:editForm }

ser_pur_pr_edit_submit:
    pattern: /pr/{id}
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:editSubmit }

ser_pur_pr_delete:
    pattern: /pr/{id}/delete
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:delete }

ser_pur_pr_grid:
    pattern: /prs/grid
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:grid }

ser_pur_pr_ajax_get:
    pattern: /ajax/pr/{id}
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:ajaxGet }

ser_pur_pr_status_approve:
    pattern: /pr/{id}/status/approve
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:statusApprove }

ser_pur_pr_status_send:
    pattern: /po/{id}/status/send
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:statusSend }

ser_pur_pr_status_cancel:
    pattern: /pr/{id}/status/cancel
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:statusCancel }

ser_pur_pr_status_fulfill:
    pattern: /po/{id}/status/fulfill
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:RequestOrder:statusFulfill }


ser_pur_del_search:
    pattern: /deliveries
    methods: [GET]
    defaults: { _controller: SereniteaBundle:Delivery:search }

ser_pur_del_post:
    pattern: /deliveries
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:Delivery:search }

ser_pur_del_index:
    pattern: /pr/{id}/deliveries
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Delivery:index }

ser_pur_del_post:
    pattern: /deliveries
    methods: [POST]
    defaults: { _controller: SereniteaBundle:Delivery:search }

ser_pur_del_add_form:
    pattern: /pr/{req_id}/delivery
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Delivery:addForm }

ser_pur_del_add_submit:
    pattern: /pr/{req_id}/delivery
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:Delivery:addSubmit }

ser_pur_del_edit_form:
    pattern: /delivery/{id}
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Delivery:editForm }

ser_pur_del_edit_submit:
    pattern: /delivery/{id}
    methods: [POST]
    defaults: { _controller: SereniteaOrderBundle:Delivery:editSubmit }

ser_pur_del_delete:
    pattern: /delivery/{id}/delete
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Delivery:delete }

ser_pur_del_check:
    pattern: /pr/mj/mj/delivery/{var_id}
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Delivery:check }

ser_receive_index:
    pattern: /incomplete
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Receive:index }

ser_receive_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Receive:grid }

ser_receive_csv:
    path: /receive/csv
    defaults: { _controller: SereniteaOrderBundle:Receive:csv }

ser_receive_print:
    path: /receive/print
    defaults: { _controller: SereniteaOrderBundle:Receive:print }

ser_receive_view:
    pattern: /incomplete/po
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Receive:view }

ser_receive_edit_form:
    pattern: /receive/po
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Receive:editForm }


ser_rlist_index:
    path:     /requestlist
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Requested:index }

ser_rlist_add_form:
    path:     /add
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Requested:addForm }

ser_rlist_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Requested:grid }

ser_rlist_csv:
    path: /requestlist/csv
    defaults: { _controller: SereniteaOrderBundle:RequestList:csv }

ser_rlist_print:
    path: /requestlist/print
    defaults: { _controller: SereniteaOrderBundle:RequestList:print }

ser_rlist_edit:
    path:     /requestlist/po
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Requested:edit }

ser_dlist_index:
    path:     /deliverylist
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Deliveries:index }

ser_dlist_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Deliveries:grid }

ser_dlist_view:
    path:     /deliverylist/receipt
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Deliveries:view }


ser_complete_index:
    pattern: /complete
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Complete:index }

ser_complete_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaOrderBundle:Complete:grid }

ser_complete_csv:
    path: /complete/csv
    defaults: { _controller: SereniteaOrderBundle:Complete:csv }

ser_complete_print:
    path: /complete/print
    defaults: { _controller: SereniteaOrderBundle:Complete:print }

ser_complete_view:
    path: /complete/po
    defaults: { _controller: SereniteaOrderBundle:Complete:view }