cat_config_index:
    pattern: /config
    methods: [GET]
    defaults: { _controller: CatalystConfigurationBundle:ConfigEntry:index }

cat_config_submit:
    pattern: /config
    methods: [POST]
    defaults: { _controller: CatalystConfigurationBundle:ConfigEntry:submit }
