#parameters:
#    catalyst_configuration.example.class: Catalyst\ConfigurationBundle\Example

services:
    catalyst_configuration:
        class: Catalyst\ConfigurationBundle\Model\ConfigurationManager
        arguments: ["@service_container"]

#    catalyst_configuration.example:
#        class: %catalyst_configuration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
