feac_sales_del_index:
    path:     /delivery
    defaults: { _controller: FareastSalesBundle:Delivery:index }

feac_sales_del_add_form:
    path:     /del
    defaults: { _controller: FareastSalesBundle:Delivery:addForm }

feac_sales_invoice_index:
    path:     /invoice
    methods:  [GET]
    defaults: { _controller: FareastSalesBundle:SalesInvoice:index }

feac_sales_invoice_add_form:
    path:     /inv
    methods:  [GET]
    defaults: { _controller: FareastSalesBundle:SalesInvoice:addForm }


cat_sales_so_index:
    path:     /sos
    methods:  [GET]
    defaults: { _controller: FareastSalesBundle:SalesOrder:index }

cat_sales_so_add_form:
    path:     /so
    defaults: { _controller: FareastSalesBundle:SalesOrder:addForm }