parameters:
#    catalyst_user.example.class: Catalyst\UserBundle\Example

services:
    catalyst_acl:
        class: Catalyst\UserBundle\Model\ACLManager
        arguments: ["@service_container"]
    catalyst_user:
        class: Catalyst\UserBundle\Model\UserManager
        arguments:
            em: "@doctrine.orm.entity_manager"
#    catalyst_user.example:
#        class: %catalyst_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
