ser_inv_pg_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:index }

ser_inv_pg_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:addForm }

ser_inv_pg_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:addSubmit }

ser_inv_pg_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:editForm }

ser_inv_pg_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:editSubmit }

ser_inv_pg_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:delete }

ser_inv_pg_grid:
    pattern: /grid/
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:grid }

ser_inv_pg_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:ProductGroup:ajaxGet }
