ser_inv_prod_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:index }

ser_inv_prod_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:addForm }

ser_inv_prod_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:Product:addSubmit }

ser_inv_prod_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:editForm }

ser_inv_prod_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:Product:editSubmit }

ser_inv_prod_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:delete }

# grid
ser_inv_prod_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:grid }

# ajax 
ser_inv_prod_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:ajaxGet }

ser_inv_prod_ajax_get_by:
    pattern: /ajax/product
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:ajaxGetBy }

ser_inv_prod_ajax_add:
    pattern: /ajax/add
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:Product:ajaxAdd }

ser_inv_prod_ajax_get:
    pattern: /ajax/product/{id}
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:ajaxGet }

# upload
ser_inv_prod_upload:
    pattern: /upload/{id}
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:Product:upload }

ser_inv_prod_upload_delete:
    pattern: /image/delete/{id}/{loop}
    defaults: { _controller: SereniteaInventoryBundle:Product:deleteImage }


# export csv
ser_inv_prod_export:
    pattern: /list/csv
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Product:exportCSV }
