acl:
    - category: Purchasing
      entries:
        - id: cat_pur.menu
          label: "Menu"
    - category: Supplier
      entries:
        - id: cat_pur_supp.menu
          label: "Menu"
        - id: cat_pur_supp.view
          label: "View"
        - id: cat_pur_supp.add
          label: "Add"
        - id: cat_pur_supp.edit
          label: "Edit"
        - id: cat_pur_supp.delete
          label: "Delete"
    - category: Purchase Order
      entries:
        - id: cat_pur_po.menu
          label: "Menu"
        - id: cat_pur_po.view
          label: "View"
        - id: cat_pur_po.add
          label: "Add"
        - id: cat_pur_po.edit
          label: "Edit"
        - id: cat_pur_po.approve
          label: "Approve"
        - id: cat_pur_po.send
          label: "Send"
        - id: cat_pur_po.fulfill
          label: "Fulfill"
        - id: cat_pur_po.cancel
          label: "Cancel"
        - id: cat_pur_po.delete
          label: "Delete"

    - category: Delivery
      entries:
        - id: cat_pur_del.add
          label: "Add"
        - id: cat_pur_del.edit
          label: "Edit"
        - id: cat_pur_del.delete
          label: "Cancel"
          
    - category: Purchase Request
      entries:
        - id: cat_pur_pr.menu
          label: "Menu"
        - id: cat_pur_pr.view
          label: "View"
        - id: cat_pur_pr.add
          label: "Add"
        - id: cat_pur_pr.edit
          label: "Edit"
        - id: cat_pur_pr.approve
          label: "Approve"
        - id: cat_pur_pr.cancel
          label: "Cancel"
        - id: cat_pur_pr.delete
          label: "Delete"