config:
    - category: "Inventory"
      entries:
        - id: catalyst_warehouse_main
          label: "Main Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
        - id: catalyst_warehouse_supplier_default
          label: "Supplier Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
