config:
    - category: "Inventory"
      entries:
        - id: catalyst_warehouse_main
          label: "Main Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
        - id: catalyst_warehouse_stock_adjustment
          label: "Stock Adjustment Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
        - id: catalyst_warehouse_production_tank
          label: "Production Tank Warehouse"
          type: select
          options_service: catalyst_inventory
          options_method: getWarehouseOptions
