menu_items:
    - id: menu_purchasing
      acl: cat_pur.menu
      label: Purchasing
      icon: fa-shopping-cart
    - id: cat_pur_supp_index
      acl: cat_pur_supp.menu
      label: Supplier
      parent: menu_purchasing
    - id: cat_pur_po_index
      acl: cat_pur_po.menu
      label: Purchase Order
      parent: menu_purchasing
    - id: cat_pur_pr_index
      acl: cat_pur_pr.menu
      label: Purchase Request
      parent: menu_purchasing
    - id: cat_pur_del_search
      acl: cat_pur_del.menu
      label: Deliveries
      parent: menu_purchasing
