parameters:
#    catalyst_purchasing.example.class: Catalyst\PurchasingBundle\Example

services:
    catalyst_purchasing:
        class: Catalyst\PurchasingBundle\Model\PurchasingManager
        arguments: [ "@doctrine.orm.entity_manager", "@security.context" ]