catalyst_menu:
    bundle_menu:
        - CatalystDashboardBundle
        - FareastSettingsBundle
        - CatalystAdminBundle
        - CatalystConfigurationBundle
        - CatalystUserBundle
        - FareastAccountingBundle
        - CatalystInventoryBundle
        - CatalystManufacturingBundle
        - CatalystPurchasingBundle
        - FareastReceivingBundle
        - FareastReportBundle
        - CatalystSalesBundle

catalyst_user:
    acl_entries:
        - id: CatalystDashboardBundle
          label: Dashboard
        - id: CatalystAdminBundle
          label: Administration
        - id: CatalystConfigurationBundle
          label: Settings
        - id: CatalystUserBundle
          label: User
        - id: CatalystInventoryBundle
          label: Inventory
        - id: CatalystManufacturingBundle
          label: Manufacturing
        - id: CatalystPurchasingBundle
          label: Purchasing      

catalyst_configuration:
    bundles:
        - CatalystPurchasingBundle
        - CatalystSalesBundle
        - CatalystServiceBundle
