catalyst_menu:
    bundle_menu:
        - CatalystDashboardBundle
        - CatalystAdminBundle
        - CatalystConfigurationBundle
        - CatalystUserBundle
        - CatalystInventoryBundle
        # - CatalystManufacturingBundle
        - CatalystPurchasingBundle
        # - CatalystSalesBundle
        - CatalystServiceBundle
        - SereniteaPurchasingBundle
        - SereniteaOrderBundle        
        - SereniteaOnlineFormsBundle        

catalyst_user:
    acl_entries:
        - id: CatalystDashboardBundle
          label: Dashboard
        - id: CatalystAdminBundle
          label: Administration
        - id: CatalystConfigurationBundle
          label: Settings
        - id: CatalystUserBundle
          label: User
        - id: CatalystInventoryBundle
          label: Inventory
        - id: CatalystManufacturingBundle
          label: Manufacturing
        - id: CatalystPurchasingBundle
          label: Purchasing
        - id: CatalystSalesBundle
          label: Sales
        - id: CatalystServiceBundle
          label: Service
        - id: SereniteaOrderBundle
          label: Requisition
        - id: SereniteaOnlineFormsBundle
          label: Online Forms        

catalyst_configuration:
    bundles:
        - CatalystPurchasingBundle
        - SereniteaPurchasingBundle
        - CatalystSalesBundle
        - CatalystServiceBundle
