ser_dashboard:
    resource: "@SereniteaDashboardBundle/Resources/config/routing.yml"
    prefix:   /

ser_purchasing:
    resource: "@SereniteaPurchasingBundle/Resources/config/routing.yml"
    prefix:   /purchasing

ser_inventory:
    resource: "@SereniteaInventoryBundle/Resources/config/child_routing.yml"
    prefix:   /inventory

ser_online_forms:
    resource: "@SereniteaOnlineFormsBundle/Resources/config/routing.yml"
    prefix:   /onlineforms

serenitea_order:
    resource: "@SereniteaOrderBundle/Resources/config/routing.yml"
    prefix:   /ordering

ser_admin:
    resource: "@SereniteaAdminBundle/Resources/config/routing.yml"
    prefix:   /

catalyst_accounting:
    resource: "@CatalystAccountingBundle/Resources/config/routing.yml"
    prefix:   /accounting

catalyst_media:
    resource: "@CatalystMediaBundle/Resources/config/routing.yml"
    prefix:   /media

catalyst_contact:
    resource: "@CatalystContactBundle/Resources/config/routing.yml"
    prefix:   /contact

catalyst_core:
    resource: "@CatalystCoreBundle/Resources/config/routing.yml"
    prefix:   /core

catalyst_service:
    resource: "@CatalystServiceBundle/Resources/config/routing.yml"
    prefix:   /service

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

catalyst_dashboard:
    resource: "@CatalystDashboardBundle/Resources/config/routing.yml"
    prefix:   /

catalyst_configuration:
    resource: "@CatalystConfigurationBundle/Resources/config/routing.yml"
    prefix:   /configuration

catalyst_sales:
    resource: "@CatalystSalesBundle/Resources/config/routing.yml"
    prefix:   /sales

catalyst_purchasing:
    resource: "@CatalystPurchasingBundle/Resources/config/routing.yml"
    prefix:   /purchasing

catalyst_manufacturing:
    resource: "@CatalystManufacturingBundle/Resources/config/routing.yml"
    prefix:   /manufacturing

catalyst_inventory:
    resource: "@CatalystInventoryBundle/Resources/config/routing.yml"
    prefix:   /inventory

catalyst_user:
    resource: "@CatalystUserBundle/Resources/config/routing.yml"
    prefix: /user
