feac_inv_begin_index:
    path:     /begin
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:Transaction:index }

feac_inv_begin_productgroup:
    path:    /begin/productgroup/{var_id}
    defaults: { _controller: FareastInventoryBundle:Transaction:getGroup }

feac_inv_begin_product:
    path:    /begin/product/{id}
    defaults: { _controller: FareastInventoryBundle:Transaction:getProduct }

feac_inv_begin_submit:
    path:    /begin
    methods: [POST]
    defaults: { _controller: FareastInventoryBundle:Transaction:addSubmit }


feac_inv_borrowed_index:
    path:     /borrowed
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:index }

feac_inv_borrowed_add_form:
    path:     /borrow
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:addForm }

feac_inv_borrowed_add_submit:
    path:     /borrow
    methods:  [POST]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:addSubmit }

feac_inv_borrowed_edit_form:
    path:     /borrow/{id}
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:editForm }

feac_inv_borrowed_edit_submit:
    pattern: /borrow/{id}
    methods: [POST]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:editSubmit }

feac_inv_borrowed_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:grid }

feac_inv_borrowed_dept:
    pattern: /borrowed/dept/{id}
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:getDept }

feac_inv_borrowed_product:
    pattern: /borrowed/product/{prod_id}
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:getProduct }

feac_inv_borrowed_export:
    pattern: /borrowed/list/csv
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:exportCSV }


feac_inv_issued_index:
    pattern:  /issued
    defaults: { _controller: FareastInventoryBundle:IssuedItem:index }

feac_inv_issued_add_form:
    pattern:  /issued/add
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:addForm }

feac_inv_issued_add_submit:
    path:     /issued/add
    methods:  [POST]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:addSubmit }

feac_inv_issued_edit_form:
    path:     /issued/edit/{id}
    methods:  [GET]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:editForm }

feac_inv_issued_edit_submit:
    pattern: /issued/edit/{id}
    methods: [POST]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:editSubmit }

feac_inv_issued_dept:
    pattern: /issued/dept/{id}
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:getDept }

feac_inv_issued_product:
    pattern: /issued/product/{prod_id}
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:IssuedItem:getProduct }



feac_inv_returned:
    path:     /returned
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:returned }


feac_inv_adjust_index:
    path:     /stock/adjust
    defaults: { _controller: FareastInventoryBundle:StockAdjustment:index }


feac_inv_transfer_index:
    path:     /stock/transfer
    defaults: { _controller: FareastInventoryBundle:TransferStock:index }

feac_inv_transfer_product:
    path:    /stock/transfer/product/{id}
    defaults: { _controller: FareastInventoryBundle:TransferStock:getProduct }

feac_inv_transfer_productgroup:
    path:    /stock/transfer/productgroup/{var_id}
    defaults: { _controller: FareastInventoryBundle:TransferStock:getGroup }

feac_inv_warehouse_index:
    path:     /stock/warehouse
    defaults: { _controller: FareastInventoryBundle:WarehouseStock:index }