feac_inv_begin_index:
    path:     /begin
    defaults: { _controller: FareastInventoryBundle:Transaction:index }

feac_inv_begin_productgroup:
    path:    /begin/productgroup/{var_id}
    defaults: { _controller: FareastInventoryBundle:Transaction:getGroup }

feac_inv_begin_product:
    path:    /begin/product/{id}
    defaults: { _controller: FareastInventoryBundle:Transaction:getProduct }

feac_inv_begin_submit:
    path:    /begin
    methods: [POST]
    defaults: { _controller: FareastInventoryBundle:Transaction:addSubmit }


feac_inv_borrowed_index:
    path:     /borrowed
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:index }

feac_inv_borrowed_add_form:
    path:     /borrowed/add
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:addForm }

feac_inv_borrowed_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:grid }

feac_inv_issued_index:
    pattern:  /issued
    defaults: { _controller: FareastInventoryBundle:Issued:index }

feac_inv_issued_add_form:
    pattern:  /issued/add
    defaults: { _controller: FareastInventoryBundle:Issued:addForm }


feac_inv_returned:
    path:     /returned
    defaults: { _controller: FareastInventoryBundle:BorrowedItems:returned }


feac_inv_adjust_index:
    path:     /stock/adjust
    defaults: { _controller: FareastInventoryBundle:StockAdjustment:index }


feac_inv_transfer_index:
    path:     /stock/transfer
    defaults: { _controller: FareastInventoryBundle:TransferStock:index }

feac_inv_warehouse_index:
    path:     /stock/warehouse
    defaults: { _controller: FareastInventoryBundle:WarehouseStock:index }