menu_items:
    - id: menu_inventory
      acl: cat_inv.menu
      label: Inventory
      icon: fa-suitcase    
    - id: feac_inv_begin_index
      label: Beginning Inventory
      parent: menu_inventory
    - id: feac_inv_borrowed_index
      label: Borrowed Items
      parent: menu_inventory
    - id: feac_inv_issued_index
      label: Issued Items
      parent: menu_inventory
    - id: feac_inv_adjust_index
      label: Stock Adjustment
      parent: menu_inventory
    - id: feac_inv_transfer_index
      label: Transfer Stock
      parent: menu_inventory
    - id: feac_inv_warehouse_index
      label: Warehouse Stock
      parent: menu_inventory
