menu_items:
    - id: cat_inv_brand_index
      acl: cat_inv_brand.menu
      label: Brand
      parent: feac_settings
    - id: menu_inventory
      acl: cat_inv.menu
      label: Inventory
      icon: fa-suitcase    
    #- id: feac_inv_begin_index
    #  label: Beginning Inventory
    #  parent: menu_inventory
    - id: cat_inv_borrowed_index
      label: Borrowed Items
      parent: menu_inventory
    - id: feac_inv_issued_index
      label: Issued Items
      parent: menu_inventory
    - id: feac_inv_transfer_index
      label: Transfer Stock
      parent: menu_inventory
    - id: cat_inv_adjust_index
      label: Stock Adjustment
      parent: menu_inventory
    - id: feac_inv_warehouse_index
      label: Warehouse Stock
      parent: menu_inventory
    - id: cat_inv_wh_index
      label: Warehouse
      parent: feac_settings
    - id: cat_inv_pg_index
      label: Product Category
      parent: feac_settings
    - id: cat_inv_fixed_asset_index
      label: Fixed Asset
      parent: feac_settings
    - id: cat_inv_prod_index
      label: Product
      parent: feac_settings
