#parameters:
#    catalyst_menu.example.class: Catalyst\MenuBundle\Example

services:
    catalyst_menu:
        class: Catalyst\MenuBundle\Model\Menu\Handler
        arguments: ["@service_container"]
        
#    catalyst_menu.example:
#        class: %catalyst_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
