config:
    - category: "User"
      entries:
        - id: catalyst_service_role_default
          label: "Default Service Role"
          type: select
          options_service: catalyst_user
          options_method: getGroupOptions
