parameters:
#    serenitea_template.example.class: Serenitea\TemplateBundle\Example

services:
#    serenitea_template.example:
#        class: %serenitea_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
