parameters:
#    catalyst_manufacturing.example.class: Catalyst\ManufacturingBundle\Example

services:
#    catalyst_manufacturing.example:
#        class: %catalyst_manufacturing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
