acl:
    - category: User
      entries:
        - id: cat_user_user.menu
          label: "Menu"
        - id: cat_user_user.view
          label: "View"
        - id: cat_user_user.add
          label: "Add"
        - id: cat_user_user.edit
          label: "Edit"
        - id: cat_user_user.delete
          label: "Delete"
    - category: Role
      entries:
        - id: cat_user_group.menu
          label: "Menu"
        - id: cat_user_group.view
          label: "View"
        - id: cat_user_group.add
          label: "Add"
        - id: cat_user_group.edit
          label: "Edit"
        - id: cat_user_group.delete
          label: "Delete"
    - category: Branch Management
      entries:
        - id: ser_inv_wh.menu
          label: "Menu"
        - id: ser_inv_wh.view
          label: "View"
        - id: ser_inv_wh.add
          label: "Add"
        - id: ser_inv_wh.edit
          label: "Edit"
        - id: ser_inv_wh.delete
          label: "Delete"