ser_inv_wh:
    resource: "@SereniteaAdminBundle/Resources/config/routes/warehouse.yml"
    prefix: /warehouses

# ser_branch_index:
#     pattern: /branches
#     methods: [GET]
#     defaults: { _controller: SereniteaAdminBundle:Branch:index }
