acl:
    - category: Inventory Order
      entries:
        - id: serenitea_order.menu
          label: "Menu"
    - category: Request List
      entries:
        - id: serenitea_rlist.menu
          label: "Menu"
        - id: serenitea_rlist.view
          label: "View"
        - id: serenitea_rlist.add
          label: "Add"
        - id: serenitea_rlist.edit
          label: "Edit"
        - id: serenitea_rlist.delete
          label: "Delete"
    - category: Deliveries List
      entries:
        - id: serenitea_dlist.menu
          label: "Menu"
        - id: serenitea_dlist.view
          label: "View"
        - id: serenitea_dlist.add
          label: "Add"
        - id: serenitea_dlist.edit
          label: "Edit"
        - id: serenitea_dlist.approve
          label: "Approve"
        - id: serenitea_dlist.send
          label: "Send"
        - id: serenitea_dlist.fulfill
          label: "Fulfill"
        - id: serenitea_dlist.cancel
          label: "Cancel"