menu_items:
    - id: menu_invorder
      acl: serenitea_order.menu
      label: Inventory Order
      icon: fa-list-alt
    - id: serenitea_rlist_index
      acl: serenitea_rlist.menu
      label: Request List
      parent: menu_invorder
    - id: serenitea_dlist_index
      acl: serenitea_dlist.menu
      label: Deliveries List
      parent: menu_invorder
