parameters:
#    catalyst_report.example.class: Serenitea\ReportBundle\Example

services:
#    catalyst_report.example:
#        class: %catalyst_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
