ser_inv_prod:
    resource: "@SereniteaInventoryBundle/Resources/config/routes/product.yml"    
    prefix:  /products

ser_inv_pg:
    resource: "@SereniteaInventoryBundle/Resources/config/routes/product_group.yml"    
    prefix:  /product_groups

ser_begin_index:
    pattern: /beginning
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Begin:index }