ser_inv_prod:
    resource: "@SereniteaInventoryBundle/Resources/config/routes/product.yml"    
    prefix:  /products

ser_inv_pg:
    resource: "@SereniteaInventoryBundle/Resources/config/routes/product_group.yml"    
    prefix:  /product_groups

ser_inv_begin_index:
    pattern: /begin
    methods: [GET]
    defaults: { _controller: SereniteaInventoryBundle:Transaction:index }

bgn_entry_ajax_add:
    pattern: /entry/ajax/add
    methods: [POST]
    defaults: { _controller: SereniteaInventoryBundle:Begin:ajaxAdd}