menu_items:
    - id: menu_inventory
      acl: ser_inv.menu
      label: Inventory
      icon: fa-suitcase
    - id: ser_inv_prod_index
      acl: ser_inv_prod.menu
      label: Supplies
      parent: menu_inventory
    - id: ser_inv_pg_index
      acl: ser_inv_pg.menu
      label: Product Category
      parent: menu_inventory
    - id: ser_begin_index
      acl: ser_begin.menu
      label: Beginning Inventory
      parent: menu_inventory