parameters:
#    serenitea_inventory.example.class: Serenitea\InventoryBundle\Example

services:
#    serenitea_inventory.example:
#        class: %serenitea_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
