feac_mfg_prod_cal:
    pattern: /production-calendar
    defaults: { _controller: FareastManufacturingBundle:Production:index }

feac_mfg_prod_cal_pdf:
    pattern: /production-calendar/pdf/{date}
    defaults: { _controller: FareastManufacturingBundle:Production:printPDF }

feac_mfg_prod_cal_ajax:
    pattern: /production-calendar/ajax/{date}
    methods: [GET]
    defaults: { _controller: FareastManufacturingBundle:Production:dailyConsumptionAjax }

feac_mfg_daily_cons:
    pattern: /daily-consumption/{date}
    methods: [GET]
    defaults: { _controller: FareastManufacturingBundle:Production:dailyConsumption }

feac_mfg_daily_cons_submit:
    pattern: /daily-consumption/{date}
    methods: [POST]
    defaults: { _controller: FareastManufacturingBundle:Production:dailyConsumptionSubmit }

feac_mfg_shift_rep_new:
    pattern: /shift-report/{date}/{shift}
    methods: [GET]
    defaults: { _controller: FareastManufacturingBundle:ShiftReport:shiftReport }

feac_mfg_shift_rep_new_submit:
    pattern: /shift-report/{date}/{shift}
    methods: [POST]
    defaults: { _controller: FareastManufacturingBundle:ShiftReport:shiftReportSubmit }

feac_mfg_shift_rep_edit:
    pattern: /shift-report/edit/{id}/{shift}
    methods: [GET]
    defaults: { _controller: FareastManufacturingBundle:ShiftReport:shiftReportEdit }

feac_mfg_shift_rep_edit_submit:
    pattern: /shift-report/edit/{id}/{shift}
    methods: [POST]
    defaults: { _controller: FareastManufacturingBundle:ShiftReport:shiftReportEditSUbmit }
