services:
    fareast_manufacturing:
        class: Fareast\ManufacturingBundle\Model\ManufacturingManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            container: "@service_container"
            security: "@security.context"

