cat_inv_prod_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:index }

cat_inv_prod_index_filter:
    pattern: /list/{filter}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:index }


cat_inv_prod_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:addForm }

cat_inv_prod_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Product:addSubmit }

cat_inv_prod_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:editForm }

cat_inv_prod_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Product:editSubmit }

cat_inv_prod_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:delete }

# grid
cat_inv_prod_stock_grid:
    pattern: /grid/{id}/stock
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:stockGrid }

cat_inv_prod_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:grid }

# ajax 
cat_inv_prod_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:ajaxGet }

cat_inv_prod_ajax_get_by:
    pattern: /ajax/product
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:ajaxGetBy }

cat_inv_prod_ajax_add:
    pattern: /ajax/add
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Product:ajaxAdd }

cat_inv_prod_ajax_get:
    pattern: /ajax/product/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:ajaxGet }

# upload
cat_inv_prod_upload:
    pattern: /upload/{id}
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Product:upload }

cat_inv_prod_upload_delete:
    pattern: /image/delete/{id}/{loop}
    defaults: { _controller: CatalystInventoryBundle:Product:deleteImage }


# export csv
cat_inv_prod_export:
    pattern: /list/csv
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Product:exportCSV }
