cat_inv_pg_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:index }

cat_inv_pg_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:addForm }

cat_inv_pg_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:addSubmit }

cat_inv_pg_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:editForm }

cat_inv_pg_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:editSubmit }

cat_inv_pg_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:delete }

cat_inv_pg_grid:
    pattern: /grid/
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:grid }

cat_inv_pg_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:ajaxGet }

cat_inv_pg_ajax_get_products:
    pattern: /ajax/{id}/products
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:ajaxGetProducts }

cat_inv_pg_ajax_get_raw_materials:
    pattern: /ajax/{id}/raw/products
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:ProductGroup:ajaxGetRawMaterials }