cat_inv_wh_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:index }

cat_inv_wh_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:addForm }

cat_inv_wh_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:addSubmit }

cat_inv_wh_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:editForm }

cat_inv_wh_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:editSubmit }

cat_inv_wh_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:delete }

cat_inv_wh_stock_grid:
    pattern: /grid/{id}/stock
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:stockGrid }

cat_inv_wh_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: CatalystInventoryBundle:Warehouse:ajaxGet }
