menu_items:
    - id: feac_receiving
      # acl: cat_dashboard.menu
      label: Receiving
      icon: fa-truck
    - id: feac_rcvng_orders
      # acl: cat_pur_supp.menu
      label: Receiving Orders
      parent: feac_receiving