menu_items:
    # - id: feac_receiving
    #   # acl: cat_dashboard.menu
    #   label: Receiving
    #   icon: fa-truck
    - id: feac_receiving_orders      
      label: Receiving Orders
      parent: menu_purchasing