feac_rcvng_orders:
    path:     /orders
    defaults: { _controller: FareastReceivingBundle:Receiving:index }

feac_rcvng_order_view:
    path:     /order/view
    defaults: { _controller: FareastReceivingBundle:Receiving:view }