feac_receiving_orders:
    path:     /orders
    defaults: { _controller: FareastReceivingBundle:Receiving:index }

feac_receiving_order_view:
    path:     /order/view
    defaults: { _controller: FareastReceivingBundle:Receiving:view }