parameters:
#    catalyst_sales.example.class: Catalyst\SalesBundle\Example

services:
    catalyst_sales:
        class: Catalyst\SalesBundle\Model\SalesManager
        arguments:
            em: "@doctrine.orm.entity_manager"
#    catalyst_sales.example:
#        class: %catalyst_sales.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
